from .accommodation import (
    Accommodation,
    AccommodationCreate,
    AccommodationType,
    AccommodationTypeCreate,
    AccommodationTypeUpdate,
    AccommodationUpdate,
)
from .booking import (
    Booking,
    BookingCheckIn,
    BookingCheckOut,
    BookingCreate,
    BookingCreateOpenDates,
    BookingCreateOpenDatesWithItems,
    BookingCreateWithItems,
    BookingPayment,
    BookingSetDates,
    BookingUpdate,
    BookingWithDetails,
    BookingWithFullDetails,
    BookingWithItems,
    CalendarEvent,
    CalendarOccupancy,
)
from .client import (
    Client,
    ClientCreate,
    ClientGroup,
    ClientGroupCreate,
    ClientGroupUpdate,
    ClientUpdate,
    ClientWithStats,
)
from .custom_item import (
    BookingCustomItem,
    BookingCustomItemCreate,
    BookingCustomItemUpdate,
    BookingCustomItemWithDetails,
    CustomItem,
    CustomItemCreate,
    CustomItemUpdate,
)
from .inventory import (
    BookingInventory,
    BookingInventoryCreate,
    BookingInventoryWithItem,
    InventoryItem,
    InventoryItemCreate,
    InventoryItemUpdate,
    InventoryItemWithType,
    InventoryType,
    InventoryTypeCreate,
    InventoryTypeUpdate,
)
from .responses import (
    AccommodationAvailabilityResponse,
    AvailableAccommodation,
    BookingActionResponse,
    CalendarStatistics,
    CurrentUserResponse,
    ErrorResponse,
    HealthCheckResponse,
    MessageResponse,
    UserRegistrationResponse,
    ValidationErrorResponse,
)
from .user import User, UserCreate, UserUpdate

__all__ = [
    # User schemas
    "User",
    "UserCreate",
    "UserUpdate",
    # Accommodation schemas
    "AccommodationType",
    "AccommodationTypeCreate",
    "AccommodationTypeUpdate",
    "Accommodation",
    "AccommodationCreate",
    "AccommodationUpdate",
    # Client schemas
    "Client",
    "ClientCreate",
    "ClientUpdate",
    "ClientGroup",
    "ClientGroupCreate",
    "ClientGroupUpdate",
    "ClientWithStats",
    # Booking schemas
    "Booking",
    "BookingCreate",
    "BookingCreateOpenDates",
    "BookingCreateWithItems",
    "BookingCreateOpenDatesWithItems",
    "BookingUpdate",
    "BookingSetDates",
    "BookingPayment",
    "BookingCheckIn",
    "BookingCheckOut",
    "BookingWithDetails",
    "BookingWithItems",
    "BookingWithFullDetails",
    "CalendarOccupancy",
    "CalendarEvent",
    # Inventory schemas
    "InventoryType",
    "InventoryTypeCreate",
    "InventoryTypeUpdate",
    "InventoryItem",
    "InventoryItemCreate",
    "InventoryItemUpdate",
    "InventoryItemWithType",
    "BookingInventory",
    "BookingInventoryCreate",
    "BookingInventoryWithItem",
    # Custom item schemas
    "CustomItem",
    "CustomItemCreate",
    "CustomItemUpdate",
    "BookingCustomItem",
    "BookingCustomItemCreate",
    "BookingCustomItemUpdate",
    "BookingCustomItemWithDetails",
    # Response schemas
    "MessageResponse",
    "UserRegistrationResponse",
    "CurrentUserResponse",
    "AccommodationAvailabilityResponse",
    "AvailableAccommodation",
    "CalendarStatistics",
    "BookingActionResponse",
    "ErrorResponse",
    "ValidationErrorResponse",
    "HealthCheckResponse",
]
